### ISSUE TITLE
Same problem here too

### ISSUE THREAD

**Issue by Samirahajiragab** [Samirahajiragab/events-calendar#3]
how can I change the calendar height?
and if there more coding that I need to add please let me know
please, thank you again 
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/55094325/77956511-fd1b1b00-729f-11ea-9049-b8c82769a3b7.png">

@HannahDelaney

**Comment by HannahDelaney** [comment]
You can address the `height` of the cells in your css. You'll need to target them specifically (based on their element type) and you can apply this. So like, within the `<tbody>`, the `<td>` elements will need to be altered.

Other required changes will just be based on the required content and screenshots. So you'll need all of the events and their corresponding colours, font size and spacing, and so on.
