### ISSUE TITLE
how to change the cell size.

### ISSUE THREAD

**Issue by Samirahajiragab** [Samirahajiragab/events-calendar#4]
how to change the cell size without me adding the padding in the main CSS, because mark pad is asking for no padding in CSS
My page seems to be shorter than the other page, I wonder why? 
@muxlowc

**Comment by muxlowc** [comment]
@Samirahajiragab  you shouldn't be using padding to get the cells bigger, but you should be telling the cells exactly what height you want them to be:

tbody td {
  height: 11em;
}
